// <auto-generated />
using System;
using Facturacion2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Facturacion2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210315050418_Facturacion1")]
    partial class Facturacion1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Facturacion2.Models.Articulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Estado");

                    b.Property<double>("Precio");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("Facturacion2.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cuenta")
                        .HasMaxLength(50);

                    b.Property<bool>("Estado");

                    b.Property<string>("Identificador")
                        .HasMaxLength(20);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Facturacion2.Models.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("facturaid");

                    b.HasKey("Id");

                    b.HasIndex("facturaid");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("Facturacion2.Models.Facturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comentario")
                        .HasMaxLength(150);

                    b.Property<string>("Fecha")
                        .HasMaxLength(10);

                    b.Property<double>("Precio_Total");

                    b.HasKey("Id");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Facturacion2.Models.Referencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DetalleId");

                    b.Property<int?>("articuloid");

                    b.Property<int?>("clientesid");

                    b.Property<int?>("vendedoresid");

                    b.HasKey("Id");

                    b.HasIndex("DetalleId");

                    b.HasIndex("articuloid");

                    b.HasIndex("clientesid");

                    b.HasIndex("vendedoresid");

                    b.ToTable("Referencia");
                });

            modelBuilder.Entity("Facturacion2.Models.Vendedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Comision");

                    b.Property<bool>("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Facturacion2.Models.Detalle", b =>
                {
                    b.HasOne("Facturacion2.Models.Facturas", "factura")
                        .WithMany()
                        .HasForeignKey("facturaid");
                });

            modelBuilder.Entity("Facturacion2.Models.Referencia", b =>
                {
                    b.HasOne("Facturacion2.Models.Detalle")
                        .WithMany("referencias")
                        .HasForeignKey("DetalleId");

                    b.HasOne("Facturacion2.Models.Articulos", "articulo")
                        .WithMany()
                        .HasForeignKey("articuloid");

                    b.HasOne("Facturacion2.Models.Clientes", "clientes")
                        .WithMany()
                        .HasForeignKey("clientesid");

                    b.HasOne("Facturacion2.Models.Vendedores", "vendedores")
                        .WithMany()
                        .HasForeignKey("vendedoresid");
                });
#pragma warning restore 612, 618
        }
    }
}
