// <auto-generated />
using System;
using APiFac3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APiFac3.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210415083009_Last Catalog")]
    partial class LastCatalog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APiFac3.Models.Articulos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("Estado");

                    b.Property<double>("Precio");

                    b.Property<int>("Stock");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("APiFac3.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cuenta")
                        .HasMaxLength(50);

                    b.Property<bool>("Estado");

                    b.Property<string>("Identificador")
                        .HasMaxLength(20);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("APiFac3.Models.Detalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cant_articulo");

                    b.Property<int>("articuloid");

                    b.Property<int>("facturaid");

                    b.HasKey("Id");

                    b.HasIndex("articuloid");

                    b.HasIndex("facturaid");

                    b.ToTable("Detalles");
                });

            modelBuilder.Entity("APiFac3.Models.Facturas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Asiento");

                    b.Property<int>("Cant_Articulos");

                    b.Property<string>("Comentario")
                        .HasMaxLength(150);

                    b.Property<string>("Fecha")
                        .HasMaxLength(10);

                    b.Property<double>("Precio_Total");

                    b.Property<int>("clienteid");

                    b.Property<int>("vendedorid");

                    b.HasKey("Id");

                    b.HasIndex("clienteid");

                    b.HasIndex("vendedorid");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("APiFac3.Models.Vendedores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cedula");

                    b.Property<double>("Comision");

                    b.Property<bool>("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("APiFac3.Models.Detalle", b =>
                {
                    b.HasOne("APiFac3.Models.Articulos", "articulos")
                        .WithMany()
                        .HasForeignKey("articuloid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("APiFac3.Models.Facturas", "factura")
                        .WithMany()
                        .HasForeignKey("facturaid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("APiFac3.Models.Facturas", b =>
                {
                    b.HasOne("APiFac3.Models.Clientes", "clientes")
                        .WithMany()
                        .HasForeignKey("clienteid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("APiFac3.Models.Vendedores", "vendedores")
                        .WithMany()
                        .HasForeignKey("vendedorid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
